# Generated by Django 2.2.7 on 2021-02-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogs_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captcha',
        ),
    ]
